# Site settings
title: Hey, I'm PC
email: zhoupc1988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   computational neuroscience and machine learning. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://zhoupc.github.io" # the base hostname & protocol for your site
twitter_username: zhoupc1988
github_username:  zhoupc
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima

gems: 
    - jemoji
